CREATE TABLE Memo (
  MemoID STRING(36) NOT NULL,
  Text STRING(65535),
) PRIMARY KEY(MemoID);

CREATE TABLE Tag (
  TagID STRING(36) NOT NULL,
  Title STRING(65535),
) PRIMARY KEY(TagID);

CREATE TABLE TagMemo (
  TagID STRING(36) NOT NULL,
  MemoID STRING(36) NOT NULL,
) PRIMARY KEY(TagID, MemoID),
  INTERLEAVE IN PARENT Tag ON DELETE CASCADE;
